### ISSUE TITLE
CMD+K to clear terminal

### ISSUE THREAD

**Issue by jjenzz** [tjx666/vscode-classic-experience#3]
CMD+K clears the terminal in VSCode but doesn't in cursor with this extension. is there something specific i need to do to get this working?

**Comment by tjx666** [comment]
@jjenzz 

Here's an optimized response in English:
In VSCode, Cmd + K serves as the keychord.leader, meaning it's used as a prefix for other keyboard shortcuts. For example:

Cmd + K, Cmd + T toggles the theme
Cmd + K, Cmd + S opens Keyboard Shortcuts settings

If you try to set Cmd + K as the shortcut for clearing the terminal, you'll encounter an issue:
When you press Cmd + K, VSCode waits for subsequent keystrokes instead of immediately executing the clear terminal command. This is because Cmd + K is already defined as a prefix for keychord sequences.
Recommendation:
Choose a different key combination for the clear terminal action. For instance, you could use Cmd + Shift + K.
This approach avoids conflicts with the existing shortcut system while providing you with an easy-to-remember and use shortcut for clearing the terminal.

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/777229a1-c90c-4b54-84a8-eb64b19dda5c">


https://code.visualstudio.com/docs/introvideos/customize

**Comment by tjx666** [comment]
I had add `cmd + shift + k` as the shortcut to `clear terminal` in this extension(latest version)

**Comment by jjenzz** [comment]
thank you for your prompt help on this, appreciate it !

**Comment by tjx666** [comment]
@jjenzz update to latest version of extension and cursor, you can use cmd+k to clear terminal now

**Comment by adiabatic** [comment]
⌘K to clear the Terminal isn't working for me yet.

This is my Cursor version:

```
Version: 0.42.5
VSCode Version: 1.93.1
Commit: 001668006cc714afd397f4ef0d52862f5a095530
Date: 2024-11-14T00:33:36.512Z
Electron: 30.4.0
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 24.1.0
```

I'm using version 2.0.1 of the extension.

When I press ⌘K in the terminal, I get this message at the bottom:

> (⌘K) was pressed. Waiting for second key of chord…

Any idea what might be weird about my setup? My shell of choice is [fish](https://fishshell.com), if that matters.

**Comment by tjx666** [comment]
@adiabatic 
try install this extension v1.x，the latest v2.x is for cursor 4.3

**Comment by adiabatic** [comment]
> @adiabatic try install this extension v1.x，the latest v2.x is for cursor 4.3

This is my cursor version now:

```
Version: 0.43.6
VSCode Version: 1.93.1
Commit: a846435528b4b760494a836f96f0739889253530
Date: 2024-12-06T05:11:55.168Z
Electron: 30.5.1
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Darwin arm64 24.2.0
```

It’s still waiting for the second key of the chord after I press ⌘K.

⇧⌘K doesn’t do anything, either.

VS Code says that I’m running version 2.0.2 of the extension.

Is there anything else that I should try to change?

**Comment by tjx666** [comment]
the cursor latest update make `cmd + k` to clear doesn't work again, I add `cmd + shift + k` keybinding again. try latest version
